name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/node.js.yml'
      - 'nodes/**'
      - 'test/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/node.js.yml'
      - 'nodes/**'
      - 'test/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python virtual environment
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('bin/pyvenv.sh') }}

    - name: Setup Python virtual environment
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            npm run venv
        elif [ "$RUNNER_OS" == "Windows" ]; then
            npm run psvenv
        else
            echo "$RUNNER_OS not supported"
            exit 1
        fi

    - name: Install dependencies
      run: npm ci

    - name: Run test suite
      run: npm test
