name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
        python-version: [3.9]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python virtual environment
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('bin/pyvenv.sh') }}

    - name: Setup Python virtual environment
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: npm run venv

    - name: Install dependencies
      run: npm ci

    - name: Run test suite
      run: npm run coverage

    - name: Log coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/*
